### ISSUE TITLE
Wrong repo url in bower.json

### ISSUE THREAD

**Issue by rightfold** [purescript-contrib/purescript-now#2]
To fix this you'll have to create a ticket here IIRC: https://github.com/bower/registry/issues/

**Comment by garyb** [comment]
What do you mean by wrong URL? It still resolves, doesn't it?

**Comment by rightfold** [comment]
https://github.com/purescript/purescript-now doesn't exist.

**Comment by garyb** [comment]
Oh, in the `bower.json` not the bower registry, I see. That field doesn't mean anything to `bower`, so it's not a problem really. Although, yeah, it should be fixed for future releases.
